---
abstract: 'Generates a tag cloud for modules used in given code'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Cloud
provides:
  Module::Cloud:
    file: lib/Module/Cloud.pm
    version: 1.100860
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  English: 0
  File::Find: 0
  File::Find::Rule::MMagic: 0
  File::Temp: 0
  FindBin: 0
  HTML::TagCloud: 0
  Module::ExtractUse: 0
  Scalar::Util: 0
  Test::More: 0.88
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Module-Cloud
  homepage: http://search.cpan.org/dist/Module-Cloud/
  repository: http://github.com/hanekomu/Module-Cloud
version: 1.100860
