--- 
abstract: Generates a tag cloud for modules used in given code
author: Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>
build_requires: 
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Module-Cloud
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Complex: 0
  File::Find::Rule::MMagic: 0
  Getopt::Attribute: 0
  HTML::TagCloud: 0
  Module::ExtractUse: 0
  perl: 5.6.0
version: 0.07
